import { defineConfig, type ExpgovConfig } from '@expgov/cli/core';

// Dogfood config for the expgov monorepo (@expgov/core public barrels).

export default defineConfig({
  packageName: '@expgov/core',
  core: {
    dir: 'packages/core',
    rootBarrel: 'packages/core/src/index.ts',
    subpaths: {
      '.': 'src/index.ts',
      './advanced': 'src/advanced/index.ts',
      './internal': 'src/internal/index.ts',
    },
  },
  tsconfig: 'tsconfig.json',
  cache: {
    enabled: true,
    dir: '.expgov/cache',
  },
  git: {
    tagPattern: 'v*',
    timelineBarrelPath: 'packages/core/src/index.ts',
  },
  tiers: {
    tag: {
      name: 'sdkTier',
      precedence: 'tag',
    },
    stable: {
      // Thin stable root — runtime/CLI host lives on ./internal; tooling on ./advanced.
      // Subpath barrels auto-hint advanced/internal via inventory subpathTierHint.
      exact: [
        'CliJsonEnvelope',
        'DiffCliOptions',
        'DoctorCliOptions',
        'SuggestCliOptions',
        'ExpgovConfig',
        'ExpgovConfigOverrides',
        'ExpgovCacheConfig',
        'ExportError',
        'ExportErrorCode',
        'GraphCliOptions',
        'InventoryCliOptions',
        'Issue',
        'IssueSeverity',
        'JsonErrorData',
        'RESULT_API_VERSION',
        'ResultMeta',
        'ResolvedTierBucket',
        'SDK_PACKAGE_NAME',
        'SDK_VERSION',
        'TierRulesConfig',
        'TierTagConfig',
        'TierPolicy',
        'TierPolicyDefinition',
        'TierPolicyRules',
        'TierRootFlatRule',
        'ResolvedTierPolicy',
        'ResolvedTierPolicyRules',
        'TierBucket',
        'TimelineCliOptions',
        'TrendCliOptions',
        'ValidateOptions',
        'defineConfig',
        'isExportError',
        'runDiff',
        'runDoctor',
        'runGraph',
        'runInventory',
        'runSuggest',
        'runTimeline',
        'runTrend',
        'runValidate',
      ],
    },
    internal: {
      // ./internal barrel also auto-hints; exact keeps inventory/graph honest if symbols appear elsewhere.
      exact: [
        'BRAND',
        'CLI_MARK',
        'CLI_NAME',
        'CommandStatus',
        'CommandTimer',
        'LogEvent',
        'LogLevel',
        'LogSink',
        'RunOptions',
        'beginCommand',
        'bootstrapRuntime',
        'buildCliJsonEnvelope',
        'buildProjectContext',
        'clearLogSinks',
        'clearProjectContext',
        'configureStyle',
        'coreLog',
        'coreLogBlank',
        'coreLogRaw',
        'coreLogTip',
        'createConsoleLogSink',
        'emitJsonError',
        'emitJsonResult',
        'emitLog',
        'finishCommand',
        'formatBoxHeader',
        'getProjectContext',
        'getRunOptions',
        'initProjectContext',
        'installDefaultLogSink',
        'printExportError',
        'printHelp',
        'printHelpHint',
        'printUnexpected',
        'resetRunOptions',
        'setProjectContext',
        'setRunOptions',
        'startCommandTimer',
        'stringifyCliCommandJson',
        'stringifyEnvelope',
        'style',
        'subscribeLogSink',
        'tryGetProjectContext',
      ],
      prefix: ['^internal[A-Z_]', 'Internal$'],
    },
    advanced: {
      exact: [
        'HelpTopic',
        'INIT_CONFIG_FILE_NAME',
        'InitDetection',
        'InitLayout',
        'InitRunOptions',
        'InitRunResult',
        'ProjectContext',
        'buildInitConfigTemplate',
        'detectInitProject',
        'detectionToConfig',
        'formatConfigDiscoveryHint',
        'formatGitCommitRangeHelp',
        'formatTimelineRangeHelp',
        'isBuiltinPolicyName',
        'policyViolatesRootFlat',
        'resolveCacheSettings',
        'resolveExpgovConfig',
        'resolveTierPolicies',
        'runInit',
      ],
      prefix: ['^experimental[A-Z_]', '^beta[A-Z_]', '^advanced[A-Z_]', 'Unsafe$'],
    },
    beta: {
      policy: 'preview',
      prefix: ['^beta'],
    },
    deprecated: {
      policy: 'deprecated',
      prefix: ['^deprecated[A-Z_]', 'Deprecated$'],
    },
  },
} satisfies ExpgovConfig);
