import { defineConfig, type ExpgovConfig } from 'expgov/core';

// Dogfood config for the expgov monorepo (@expgov/core public barrel).

export default defineConfig({
  packageName: '@expgov/core',
  core: {
    dir: 'packages/core',
    rootBarrel: 'packages/core/src/index.ts',
    subpaths: {
      '.': 'src/index.ts',
    },
  },
  tsconfig: 'tsconfig.json',
  cacheDir: '.expgov/cache',
  git: {
    tagPattern: 'v*',
    timelineBarrelPath: 'packages/core/src/index.ts',
  },
  tiers: {
    stable: {
      exact: [
        'BRAND',
        'CLI_MARK',
        'CLI_NAME',
        'CliJsonEnvelope',
        'CommandStatus',
        'CommandTimer',
        'DiffCliOptions',
        'DoctorCliOptions',
        'ExpgovConfig',
        'ExpgovConfigOverrides',
        'ExportError',
        'ExportErrorCode',
        'GraphCliOptions',
        'HelpTopic',
        'INIT_CONFIG_FILE_NAME',
        'InitDetection',
        'InitLayout',
        'InitRunOptions',
        'InitRunResult',
        'InventoryCliOptions',
        'Issue',
        'IssueSeverity',
        'LogEvent',
        'LogLevel',
        'LogSink',
        'ProjectContext',
        'RESULT_API_VERSION',
        'ResultMeta',
        'RunOptions',
        'TierRulesConfig',
        'TierBucket',
        'TimelineCliOptions',
        'TrendCliOptions',
        'ValidateOptions',
        'beginCommand',
        'bootstrapRuntime',
        'clearLogSinks',
        'clearProjectContext',
        'configureStyle',
        'coreLog',
        'coreLogBlank',
        'coreLogRaw',
        'coreLogTip',
        'createConsoleLogSink',
        'defineConfig',
        'detectInitProject',
        'detectionToConfig',
        'finishCommand',
        'installDefaultLogSink',
        'initProjectContext',
        'printExportError',
        'printHelp',
        'printHelpHint',
        'printUnexpected',
        'startCommandTimer',
        'stringifyCliCommandJson',
        'stringifyEnvelope',
        'style',
        'subscribeLogSink',
        'tryGetProjectContext',
      ],
      prefix: [
        'run',
        'build',
        'emit',
        'get',
        'set',
        'reset',
        'is',
        'format',
        'resolve',
        'walk',
        'directory',
        'normalize',
        'rethrow',
        'noop',
      ],
    },
    internal: {
      prefix: ['^internal[A-Z_]', 'Internal$'],
    },
    advanced: {
      prefix: ['^experimental[A-Z_]', '^beta[A-Z_]', '^advanced[A-Z_]', 'Unsafe$'],
    },
  },
} satisfies ExpgovConfig);
